### ISSUE TITLE
Wrong behavior for maps

### ISSUE THREAD

**Issue by fedulovivan** [Zhwt/yaml-to-go#2]
Given following yaml input
```yaml
users:
  1:
    name: John Doe
    age: 30
    email: john.doe@example.com
  2:
    name: Ivan
    age: 40
    email: ivan@main.com
```
Expected result is
(its acceptable to see string instead of int for map key)
```go
type AutoGenerated struct {
	Users map[int]User `yaml:"users"`
}
type User struct {
	Name  string `yaml:"name"` 
	Age     int       `yaml:"age"`  
	Email  string  `yaml:"email"`
}
```
Actual result is
```go
type AutoGenerated struct {
	Users Users `yaml:"users"`
}
type Num1 struct {
	Name  string `yaml:"name"`
	Age     int       `yaml:"age"`
	Email   string `yaml:"email"`
}
type Num2 struct {
	Name  string `yaml:"name"`
	Age   int    `yaml:"age"`
	Email string `yaml:"email"`
}
type Users struct {
	Num1 Num1 `yaml:"1"`
	Num2 Num2 `yaml:"2"`
}
```
BTW There is an alternative tool https://jsonformatter.org/yaml-to-go which is not ideal, but gives better results for map.
